version: "3.9"

networks:
  bz-network:
    name: bz-network
    driver: bridge

services:
  bz-gateway:
    build: .
    container_name: bz-gateway
    image: bz-gateway:latest
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ${PWD}:/app
    ports:
      - 3000:3000
    networks:
      - bz-network
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=A0u48RmVh3S3
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - bz-network

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: B5Ia4v39YUIz
    ports:
      - 5432:5432
    networks:
    - bz-network